export const ADD_FILM = 'ADD_FILM'
export const ADD_FILM_OK = 'ADD_FILM_OK'
export const ADD_FILM_ERROR = 'ADD_FILM_ERROR'

export const START_DOWNLOAD_FILMS = 'START_DOWNLOAD_FILMS'
export const DOWNLOAD_FILMS_OK = 'DOWNLOAD_FILMS_OK'
export const DOWNLOAD_FILMS_ERROR = 'DOWNLOAD_FILMS_ERROR'

export const GET_FILM_REMOVED = 'GET_FILM_REMOVED'
export const FILM_REMOVED_OK = 'FILM_REMOVED_OK'
export const FILM_REMOVED_ERROR = 'FILM_REMOVED_ERROR'

export const GET_FILM_EDIT = 'GET_FILM_EDIT'
export const START_FILM_EDITION = 'START_FILM_EDITION'
export const FILM_EDITED_OK = 'FILM_EDITED_OK'
export const FILM_EDITED_ERROR = 'FILM_EDITED_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
